version: '3.9'

services:
  core:
    build:
      context: ./dockerfiles
      dockerfile: pnpm.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: core
    volumes:
      - .:/src
    working_dir: /src

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    image: backend
    environment:
      APP_NAME: 'backend service in docker'
    ports:
      - 5001:5001
    networks:
      - backend-realworld-network

  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

volumes:
  db:


networks:
  backend-realworld-network:
